name:                      Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name:                  Release binary
    strategy:
      matrix:
        include:
          - os:            ubuntu-latest
            target:        x86_64-unknown-linux-gnu
            file_name:     libstop_the_world.so
            artifact_name: libstop_the_world-x86_64-unknown-linux-gnu.so
          # - os:          ubuntu-latest
            # target:      aarch64-unknown-linux-gnu
            # file_name:   libstop_the_world.so
            # artifact_name: libstop_the_world-aarch64-unknown-linux-gnu.so
          - os:            ubuntu-latest
            target:        armv7-unknown-linux-gnueabihf
            file_name:     libstop_the_world.so
            artifact_name: libstop_the_world-armv7-unknown-linux-gnueabihf.so
          # This repository is not for Windows.
          # - os:          windows-latest
            # target:      x86_64-pc-windows-msvc
            # file_name:   stop_the_world.dll
            # artifact_name: stop_the_world-x86_64-pc-windows-msvc.dll
          # - os:          windows-latest
            # target:      x86_64-pc-windows-gnu
            # file_name:   stop_the_world.dll
            # artifact_name: stop_the_world-x86_64-unknown-linux-gnu.dll
          - os:            macos-latest
            target:        x86_64-apple-darwin
            file_name:     libstop_the_world.dylib
            artifact_name: libstop_the_world-x86_64-apple-darwin.dylib
          # - os:          macos-latest
            # target:      aarch64-apple-darwin
            # file_name:   libstop_the_world.dylib
            # artifact_name: libstop_the_world-aarch64-apple-darwin.dylib

    runs-on:               ${{ matrix.os }}

    steps:
      - uses:              actions/checkout@v2
      - uses:              actions-rs/toolchain@v1
        with:
          toolchain:       stable
          target:          ${{ matrix.target }}
          override:        true

      - name:              Build
        uses:              actions-rs/cargo@v1
        with:
          use-cross:       true
          command:         build
          args:            --release --target ${{ matrix.target }} --verbose

      - name:              Upload binaries to release
        uses:              svenstaro/upload-release-action@2.1.1
        with:
          repo_token:      ${{ secrets.GITHUB_TOKEN }}
          file:            target/${{ matrix.target }}/release/${{ matrix.file_name }}
          asset_name:      ${{ matrix.artifact_name }}
          tag:             ${{ github.ref }}
          overwrite:       true
